version: '3'

services:
  database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: kuoris
      MARIADB_USER: kuoris
      MARIADB_PASSWORD: kuoris
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    depends_on:
      - database
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - '8080:8080'

volumes:
  db-data:
